
#ifndef OCARINA_SONG_KEYS_H_
#define OCARINA_SONG_KEYS_H_

#define OCARINA_SONG_MAX_NAME_LENGTH 32
#define OCARINA_MAX_SONG_KEYS 8
#define OCARINA_NUM_SONGS 

typedef enum OcarinaKey_t
{
  OCARINA_KEY_A = 0,  // D4
  OCARINA_KEY_X,      // B4
  OCARINA_KEY_Y,      // A4
  OCARINA_KEY_L,      // D3
  OCARINA_KEY_R,      // F3
} OcarinaKey;


typedef struct OcarinaKeySet_t {
  const char Name[OCARINA_SONG_MAX_NAME_LENGTH];
  int NumKeys;
  OcarinaKey Keys[OCARINA_MAX_SONG_KEYS];
} OcarinaKeySet;


const OcarinaKeySet OcarinaSongKeySets[] =
{
  {"Zelda's Lullaby",    6, [OCARINA_KEY_X,  OCARINA_KEY_A,  OCARINA_KEY_Y,  OCARINA_KEY_X,  OCARINA_KEY_A,  OCARINA_KEY_Y]},
  {"Epona's Song",       6, [OCARINA_KEY_A,  OCARINA_KEY_X,  OCARINA_KEY_Y,  OCARINA_KEY_A,  OCARINA_KEY_X,  OCARINA_KEY_Y]},
  {"Saria's Song",       6, [OCARINA_KEY_R,  OCARINA_KEY_Y,  OCARINA_KEY_X,  OCARINA_KEY_R,  OCARINA_KEY_Y,  OCARINA_KEY_X]},
  {"Song of Storms",     6, [OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_A,  OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_A]},
  {"Sun's Song",         6, [OCARINA_KEY_Y,  OCARINA_KEY_R,  OCARINA_KEY_A,  OCARINA_KEY_Y,  OCARINA_KEY_R,  OCARINA_KEY_A]},
  {"Song of Time",       6, [OCARINA_KEY_Y,  OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_Y,  OCARINA_KEY_L,  OCARINA_KEY_R]},
  {"Minuet of Forest",   6, [OCARINA_KEY_L,  OCARINA_KEY_A,  OCARINA_KEY_X,  OCARINA_KEY_Y,  OCARINA_KEY_X,  OCARINA_KEY_Y]},
  {"Bolero of Fire",     8, [OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_Y,  OCARINA_KEY_R,  OCARINA_KEY_Y,  OCARINA_KEY_R]},
  {"Serenade of Water",  5, [OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_Y,  OCARINA_KEY_Y,  OCARINA_KEY_X]},
  {"Requiem of Spirit",  6, [OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_Y,  OCARINA_KEY_R,  OCARINA_KEY_L]},
  {"Nocturne of Shadow", 7, [OCARINA_KEY_X,  OCARINA_KEY_Y,  OCARINA_KEY_Y,  OCARINA_KEY_L,  OCARINA_KEY_X,  OCARINA_KEY_Y,  OCARINA_KEY_R]},
  {"Prelude of Light",   6, [OCARINA_KEY_A,  OCARINA_KEY_Y,  OCARINA_KEY_A,  OCARINA_KEY_Y,  OCARINA_KEY_X,  OCARINA_KEY_A]}
  // {"Scarecrow's Song",   8, [OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_R,  OCARINA_KEY_L,  OCARINA_KEY_R]}
};

#endif // OCARINA_SONG_KEYS_H_
