
#include "Song.h"

const SongNotes BonusBonus = {
  "Bonus Bonus",
  114,  // Tempo
  65,   // Number of Notes
  {
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_A4, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_A4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_G4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_G4, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_G4, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_G4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_F4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_F4, NOTE_TYPE_QUARTER, 0},
    {NOTE_G4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_G4, NOTE_TYPE_QUARTER, 0},
    {NOTE_F4, NOTE_TYPE_HALF, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_A4, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_A4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_G4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_C5, NOTE_TYPE_QUARTER, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_F4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_F4, NOTE_TYPE_QUARTER, 0},
    {NOTE_G4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 1},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_G4, NOTE_TYPE_QUARTER, 0},
    {NOTE_F4, NOTE_TYPE_HALF, 0},
  }
};