
#include "Song.h"

const SongNotes RightRound = {
  "RightRound",
  125,  // Tempo
  116,   // Number of Notes
  {
    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_C4, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_C3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_C3, NOTE_TYPE_QUARTER, 0}
  }
};
