
#include "Song.h"

const SongNotes BoleroOfFire = {
  "Bolero of Fire",
  62,  // Tempo
  55,   // Number of Notes
  {
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_F3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_F4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_BF3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_BF3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_G3, NOTE_TYPE_SIXTEENTH, 1},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_G4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_G4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},

    //--

    {NOTE_D3, NOTE_TYPE_HALF_DOT, 0},
  }
};
