
#include "Song.h"

SongNotes EponasSong = {
  "Epona's Song",
  100,  // Tempo
  42,   // Number of Notes
  {
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 1},

    // --

    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_F3, NOTE_TYPE_QUARTER, 0},

    // --
    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_CS4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_HALF, 1},
    {NOTE_B3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_D4, NOTE_TYPE_HALF, 1},
    {NOTE_D4, NOTE_TYPE_QUARTER, 0},
    {NOTE_CS4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},

    // --

    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // +++

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},

    // --

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 1},

    // --

    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_HALF, 1},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
  }
};
