
#include "Song.h"

const SongNotes Margaritaville = {
  "Margaritaville",
  125,  // Tempo
  163,   // Number of Notes
  {
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_DOT, 0},

    //--

    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_DOT, 0},

    //--

    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_FS3, NOTE_TYPE_HALF, 0},
    {NOTE_E3, NOTE_TYPE_HALF, 0},

    //--

    {NOTE_D3, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A2, NOTE_TYPE_QUARTER, 0},
    {NOTE_CS3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_D3, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_E3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_D3, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 1},
    
    //--

    {NOTE_A3, NOTE_TYPE_HALF, 0},
    {NOTE_E3, NOTE_TYPE_HALF, 1},

    //--

    {NOTE_E3, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},

    //--

    {NOTE_G3, NOTE_TYPE_HALF, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_E3, NOTE_TYPE_HALF, 0},

    //--

    {NOTE_G3, NOTE_TYPE_HALF, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_E3, NOTE_TYPE_HALF, 0},

    //--

    {NOTE_A3, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_D3, NOTE_TYPE_HALF_DOT, 0},

    //--

    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_DOT, 1},

    //--

    {NOTE_B3, NOTE_TYPE_QUARTER_DOT, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D3, NOTE_TYPE_QUARTER_DOT, 0},
    {NOTE_FS3, NOTE_TYPE_QUARTER_DOT, 0},

    //--

    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_DOT, 1},
    
    //--

    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 1},

    //--

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 1},
    
    //--

    {NOTE_FS3, NOTE_TYPE_QUARTER_DOT, 0},
    {NOTE_D3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_D3, NOTE_TYPE_HALF, 0},

    //--

    {NOTE_FS3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_DOT, 1},

    //--

    {NOTE_B3, NOTE_TYPE_QUARTER, 1},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_CS4, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_CS4, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_CS4, NOTE_TYPE_QUARTER_DOT, 0},

    //--

    {NOTE_D4, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_G3, NOTE_TYPE_HALF, 1},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_QUARTER, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 1},
    {NOTE_G3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_FS3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D3, NOTE_TYPE_EIGHTH, 1},

    //--

    {NOTE_D3, NOTE_TYPE_QUARTER, 0}
  }
};