
#include "Song.h"

SongNotes SongOfStorms = {
  "Song of Storms",
  180,  // Tempo
  35,   // Number of Notes
  {
    {NOTE_D3, NOTE_TYPE_EIGHTH},
    {NOTE_F3, NOTE_TYPE_EIGHTH},
    {NOTE_D4, NOTE_TYPE_HALF},

    {NOTE_D3, NOTE_TYPE_EIGHTH},
    {NOTE_F3, NOTE_TYPE_EIGHTH},
    {NOTE_D4, NOTE_TYPE_HALF},

    {NOTE_E4, NOTE_TYPE_QUARTER_DOT},
    {NOTE_F4, NOTE_TYPE_EIGHTH},
    {NOTE_E4, NOTE_TYPE_EIGHTH},
    {NOTE_F4, NOTE_TYPE_EIGHTH},

    {NOTE_E4, NOTE_TYPE_EIGHTH},
    {NOTE_C4, NOTE_TYPE_EIGHTH},
    {NOTE_A4, NOTE_TYPE_HALF},
    //13


    {NOTE_A4, NOTE_TYPE_QUARTER},
    {NOTE_D3, NOTE_TYPE_QUARTER},
    {NOTE_F3, NOTE_TYPE_EIGHTH},
    {NOTE_G3, NOTE_TYPE_EIGHTH},

    {NOTE_A4, NOTE_TYPE_HALF_DOT},

    {NOTE_E4, NOTE_TYPE_QUARTER_DOT},
    {NOTE_F4, NOTE_TYPE_EIGHTH},
    {NOTE_E4, NOTE_TYPE_EIGHTH},
    {NOTE_F4, NOTE_TYPE_EIGHTH},
    //9


    {NOTE_D3, NOTE_TYPE_EIGHTH},
    {NOTE_F3, NOTE_TYPE_EIGHTH},
    {NOTE_D4, NOTE_TYPE_HALF},
    
    {NOTE_D3, NOTE_TYPE_EIGHTH},
    {NOTE_F3, NOTE_TYPE_EIGHTH},
    {NOTE_D4, NOTE_TYPE_HALF},

    {NOTE_E4, NOTE_TYPE_QUARTER_DOT},
    {NOTE_F4, NOTE_TYPE_EIGHTH},
    {NOTE_E4, NOTE_TYPE_EIGHTH},
    {NOTE_F4, NOTE_TYPE_EIGHTH},

    {NOTE_E4, NOTE_TYPE_EIGHTH},
    {NOTE_C4, NOTE_TYPE_EIGHTH},
    {NOTE_A4, NOTE_TYPE_HALF}
    //13
  }
};
