
#include "Song.h"

// Sheet music
//  https://musescore.com/user/20360426/scores/4880846

const SongNotes ZeldaTheme = {
  "Zelda Theme",
  136,   // Tempo
  139,   // Number of Notes
  {
    {NOTE_A3, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER_TRIPLET_DOUBLE, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // --

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET_DOUBLE, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER_TRIPLET_DOUBLE, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // --

    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET_DOUBLE, 0},
    {NOTE_G3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER_TRIPLET_DOUBLE, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // --

    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    
    // --

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_E3, NOTE_TYPE_QUARTER_DOT, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_B3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    // +++

    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_F4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_G4, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // -- 

    {NOTE_A4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_A4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_G4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_F4, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // --

    {NOTE_G4, NOTE_TYPE_EIGHTH_DOT, 0},
    {NOTE_F4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_E4, NOTE_TYPE_QUARTER, 0},

    // -- 

    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_F4, NOTE_TYPE_HALF, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},

    // -- 

    {NOTE_C4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_C4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_D4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_C4, NOTE_TYPE_EIGHTH, 0},

    // --

    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_DS4, NOTE_TYPE_HALF, 0},
    {NOTE_FS4, NOTE_TYPE_QUARTER, 0},

    // +++

    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},

    // --

    {NOTE_A3, NOTE_TYPE_QUARTER, 0},
    {NOTE_E3, NOTE_TYPE_QUARTER_DOT, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_B3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_D4, NOTE_TYPE_SIXTEENTH, 0},

    // -- 

    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_F4, NOTE_TYPE_QUARTER_TRIPLET, 0},
    {NOTE_G4, NOTE_TYPE_QUARTER_TRIPLET, 0},

    // --

    {NOTE_A4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_C5, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_B4, NOTE_TYPE_QUARTER, 0},
    {NOTE_GS4, NOTE_TYPE_HALF, 0},
    {NOTE_E4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_F4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_GS4, NOTE_TYPE_QUARTER, 0},
    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_E4, NOTE_TYPE_QUARTER, 0},

    // +++

    {NOTE_F4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_A4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_GS4, NOTE_TYPE_QUARTER, 0},
    {NOTE_E4, NOTE_TYPE_HALF, 0},
    {NOTE_CS4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_D4, NOTE_TYPE_HALF, 0},
    {NOTE_REST, NOTE_TYPE_QUARTER, 0},
    {NOTE_F4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_E4, NOTE_TYPE_QUARTER, 0},
    {NOTE_C4, NOTE_TYPE_HALF, 0},
    {NOTE_A3, NOTE_TYPE_QUARTER, 0},

    // -- 

    {NOTE_B3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_B3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_CS4, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_DS4, NOTE_TYPE_HALF, 0},
    {NOTE_FS4, NOTE_TYPE_QUARTER, 0},

    // --

    {NOTE_E4, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_SIXTEENTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_E3, NOTE_TYPE_EIGHTH, 0},
    {NOTE_A3, NOTE_TYPE_EIGHTH, 0},
  }
};
